[background]
path = "/etc/greetd/wallpaper.png"
fit = "Cover"

[GTK]
application_prefer_dark_theme = true

[commands]
reboot = ["systemctl", "reboot"]
poweroff = ["systemctl", "poweroff"]

[appearance]
greeting_msg = "Welcome back."
